version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/"
    schedule:
      interval: "monthly"
    groups:
      ruby-dependencies:
        update-types:
          - "minor"
          - "patch"
