version: "3.8"

services:
  postgres:
    image: postgres:15.1
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=ruby-getting-started
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=ruby-getting-started_development
  app:
    stdin_open: true
    tty: true
    build: .
    image: ruby-getting-started-development:latest
    command: /bin/sh -c "rm -f /app/tmp/pids/server.pid && ./bin/dev"
    volumes:
      - .:/app
      # don't mount tmp directory - something weird with bootsnap:	
      # https://github.com/Shopify/bootsnap/issues/177#issuecomment-491711481	
      - /app/tmp
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    links:
      - postgres
    environment:
      - RUBYOPT=-W:no-deprecated -W:no-experimental
      - DATABASE_URL=postgres
      - DATABASE_NAME=ruby-getting-started_development
      - DATABASE_USERNAME=ruby-getting-started
      - DATABASE_PASSWORD=password
